// Project photos (owner uploads to the old site, captured 5 Oct 2026; resized, EXIF/GPS stripped).
// Alt text describes what the photo shows. No photo is tied to a city or client until Walter confirms it.
export type Photo = { id: string; alt: string; tags: string[]; lg: Img; sm: Img; lowRes: boolean; source: string };
export type Img = { src: string; w: number; h: number };

export const PHOTOS: Photo[] = [
  { id: 'white-kitchen-marble', alt: "White kitchen with marble backsplash and a wide-plank wood floor", tags: ["kitchen", "flooring"], lg: {"src": "/images/white-kitchen-marble-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/white-kitchen-marble-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '5714d7e7-68e7-4310-88df-738fe8fb4736.jpg' },
  { id: 'wood-ceiling-kitchen', alt: "Kitchen with a wood-plank ceiling, wood cabinets and a center island", tags: ["kitchen", "cabinetry"], lg: {"src": "/images/wood-ceiling-kitchen-lg.jpg", "w": 639, "h": 428}, sm: {"src": "/images/wood-ceiling-kitchen-lg.jpg", "w": 639, "h": 428}, lowRes: true, source: '69699530-4450-44c3-9446-de9f50cfd4c5.jpg' },
  { id: 'double-vanity-bathroom', alt: "Bathroom with a long double vanity, grey cabinets and a full-width mirror", tags: ["bathroom"], lg: {"src": "/images/double-vanity-bathroom-lg.jpg", "w": 1600, "h": 1200}, sm: {"src": "/images/double-vanity-bathroom-sm.jpg", "w": 800, "h": 600}, lowRes: false, source: '05be803d-e263-4ff1-ae41-45117adf7e7d.jpg' },
  { id: 'herringbone-floor', alt: "Herringbone hardwood floor", tags: ["flooring"], lg: {"src": "/images/herringbone-floor-lg.jpg", "w": 600, "h": 450}, sm: {"src": "/images/herringbone-floor-lg.jpg", "w": 600, "h": 450}, lowRes: true, source: '26e9015a-1bc3-4be9-ab43-61cbb17500a7.jpg' },
  { id: 'entry-hall-hardwood', alt: "Two-storey entry hall with a balcony and hardwood floor", tags: ["flooring", "remodel"], lg: {"src": "/images/entry-hall-hardwood-lg.jpg", "w": 402, "h": 600}, sm: {"src": "/images/entry-hall-hardwood-lg.jpg", "w": 402, "h": 600}, lowRes: true, source: '945c2bf2-7384-4cd8-aece-0b3f39e02fcd.jpg' },
  { id: 'site-work', alt: "Site work with a skid steer before construction", tags: ["construction"], lg: {"src": "/images/site-work-lg.jpg", "w": 1170, "h": 867}, sm: {"src": "/images/site-work-sm.jpg", "w": 800, "h": 593}, lowRes: false, source: 'c5588c0f-7322-4cb9-9546-7a90f793fd27.jpg' },
  { id: 'stair-tread-finishing', alt: "Stair treads being finished", tags: ["carpentry", "flooring"], lg: {"src": "/images/stair-tread-finishing-lg.jpg", "w": 800, "h": 600}, sm: {"src": "/images/stair-tread-finishing-lg.jpg", "w": 800, "h": 600}, lowRes: true, source: '52116931-51e9-4c40-b056-38aab8290de1.jpg' },
  { id: 'bedroom-wide-plank', alt: "Bedroom with a wide-plank hardwood floor", tags: ["flooring"], lg: {"src": "/images/bedroom-wide-plank-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/bedroom-wide-plank-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '8ed7dd36-caaa-42fe-a1cd-e5ed4f131313.jpg' },
  { id: 'walter-contreras', alt: "Walter Contreras on a job site", tags: ["people"], lg: {"src": "/images/walter-contreras-lg.jpg", "w": 1168, "h": 1561}, sm: {"src": "/images/walter-contreras-sm.jpg", "w": 599, "h": 800}, lowRes: false, source: '1b9be129-2293-4e78-8113-bf6d96a08661.png' },
  { id: 'addition-in-progress', alt: "Home addition in progress with a telehandler on site", tags: ["construction", "addition"], lg: {"src": "/images/addition-in-progress-lg.jpg", "w": 960, "h": 1280}, sm: {"src": "/images/addition-in-progress-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: 'fac6c5f5-84c5-4ec4-a299-05f67d1da0c2.jpg' },
  { id: 'marble-island-kitchen', alt: "Kitchen with a marble waterfall island and light oak floor", tags: ["kitchen", "cabinetry", "flooring"], lg: {"src": "/images/marble-island-kitchen-lg.jpg", "w": 960, "h": 1280}, sm: {"src": "/images/marble-island-kitchen-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '05fff3cd-de58-46d5-ab89-28adf6dcd12a.jpg' },
  { id: 'tile-stair-railing', alt: "Staircase with patterned tile risers and an iron railing", tags: ["carpentry", "remodel"], lg: {"src": "/images/tile-stair-railing-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/tile-stair-railing-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '71ca267f-3ba7-4813-b480-cc1aaa6e38a9.jpg' },
  { id: 'framing-telehandler', alt: "Second-storey framing with a telehandler lifting materials", tags: ["construction", "addition"], lg: {"src": "/images/framing-telehandler-lg.jpg", "w": 960, "h": 1280}, sm: {"src": "/images/framing-telehandler-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '869a6847-ee37-4309-b4fe-ae957812254d.jpg' },
  { id: 'beam-ceiling-kitchen', alt: "Kitchen with wood beam ceiling and built-in wood cabinetry", tags: ["kitchen", "cabinetry"], lg: {"src": "/images/beam-ceiling-kitchen-lg.jpg", "w": 700, "h": 467}, sm: {"src": "/images/beam-ceiling-kitchen-lg.jpg", "w": 700, "h": 467}, lowRes: true, source: 'df78be93-2ef0-46c0-8817-1f5c633b0bd8.jpg' },
  { id: 'built-in-shelving-kitchen', alt: "Kitchen with built-in open shelving and stainless refrigerator", tags: ["kitchen", "cabinetry"], lg: {"src": "/images/built-in-shelving-kitchen-lg.jpg", "w": 960, "h": 1600}, sm: {"src": "/images/built-in-shelving-kitchen-sm.jpg", "w": 480, "h": 800}, lowRes: false, source: '18e79a83-1a9f-45ab-8238-8d6b9795eed5.jpg' },
  { id: 'patterned-tile-bathroom', alt: "Bathroom with patterned floor tile and a glass shower", tags: ["bathroom"], lg: {"src": "/images/patterned-tile-bathroom-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/patterned-tile-bathroom-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: 'd95fe9be-7420-4203-a2d8-213f25d4127d.jpg' },
  { id: 'marble-shower', alt: "Walk-in shower with marble-look tile and frameless glass", tags: ["bathroom"], lg: {"src": "/images/marble-shower-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/marble-shower-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '635ad09d-614f-49cd-90c5-a0359fa369e8.jpg' },
  { id: 'tub-and-shower', alt: "Bathroom with a freestanding tub and glass shower", tags: ["bathroom"], lg: {"src": "/images/tub-and-shower-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/tub-and-shower-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '4e1f37bd-7c5a-4d75-a74e-77b9ebca2204.jpg' },
  { id: 'freestanding-tub-bathroom', alt: "Bathroom with a freestanding tub, glass shower and tile floor", tags: ["bathroom"], lg: {"src": "/images/freestanding-tub-bathroom-lg.jpg", "w": 1600, "h": 1200}, sm: {"src": "/images/freestanding-tub-bathroom-sm.jpg", "w": 800, "h": 600}, lowRes: false, source: 'f83adcb7-f1d4-40bb-9854-05163ed64ce1.jpg' },
  { id: 'dark-tile-bathroom', alt: "Bathroom with dark tile, built-in tub and white vanity", tags: ["bathroom"], lg: {"src": "/images/dark-tile-bathroom-lg.jpg", "w": 1600, "h": 1200}, sm: {"src": "/images/dark-tile-bathroom-sm.jpg", "w": 800, "h": 600}, lowRes: false, source: 'bed92d73-1589-42c9-a80c-50374e1d29cc.jpg' },
  { id: 'floating-vanity', alt: "Dark floating vanity with under-cabinet lighting", tags: ["bathroom", "cabinetry"], lg: {"src": "/images/floating-vanity-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/floating-vanity-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '82e3841d-6625-4873-9d96-05be3b33fe56.jpg' },
  { id: 'white-vanity', alt: "White vanity with marble top and wainscot panelling", tags: ["bathroom", "cabinetry"], lg: {"src": "/images/white-vanity-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/white-vanity-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: 'ab40ebf7-3e08-47e6-9054-0bfc6d40e625.jpg' },
  { id: 'grey-tile-bathroom', alt: "Bathroom with grey wall tile, patterned floor and freestanding tub", tags: ["bathroom"], lg: {"src": "/images/grey-tile-bathroom-lg.jpg", "w": 1600, "h": 1200}, sm: {"src": "/images/grey-tile-bathroom-sm.jpg", "w": 800, "h": 600}, lowRes: false, source: 'cb7ff949-3846-4869-8d62-ecd425a3f198.jpg' },
  { id: 'stair-install', alt: "Staircase installation in progress", tags: ["carpentry"], lg: {"src": "/images/stair-install-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/stair-install-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: 'c64f55b6-2385-4d50-9b21-fd8cbe04ea5b.jpg' },
  { id: 'light-oak-floor-stair', alt: "Light oak floor through an open living area and staircase", tags: ["flooring", "carpentry"], lg: {"src": "/images/light-oak-floor-stair-lg.jpg", "w": 1600, "h": 1200}, sm: {"src": "/images/light-oak-floor-stair-sm.jpg", "w": 800, "h": 600}, lowRes: false, source: 'b9714e4a-2a6e-49e2-93d0-7e2ffb487f61.jpg' },
  { id: 'door-install', alt: "Installing a large glass door system", tags: ["construction"], lg: {"src": "/images/door-install-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/door-install-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '7b2cc29e-6071-4743-9d9c-287b40795a8a.jpg' },
  { id: 'glass-panel-install', alt: "Setting a glass panel during installation", tags: ["construction"], lg: {"src": "/images/glass-panel-install-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/glass-panel-install-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '5d0c0b72-2651-4ec8-beec-dfe54489702b.jpg' },
  { id: 'oak-floor-fireplace', alt: "Living room with light oak floor and a marble fireplace", tags: ["flooring", "remodel"], lg: {"src": "/images/oak-floor-fireplace-lg.jpg", "w": 1200, "h": 1600}, sm: {"src": "/images/oak-floor-fireplace-sm.jpg", "w": 600, "h": 800}, lowRes: false, source: '7ff0c17f-87d0-4f4c-b602-d98c7f738f9e.jpg' },
];

export const photo = (id: string): Photo => {
  const p = PHOTOS.find((x) => x.id === id);
  if (!p) throw new Error(`unknown photo ${id}`);
  return p;
};
export const tagged = (t: string) => PHOTOS.filter((p) => p.tags.includes(t));
